### ISSUE TITLE
Error: inlining failed in call to ‘always_inline’

### ISSUE THREAD

**Issue by yifangt** [jermp/sshash#1]
I tried to compile the package to give it a try but met a problem at compiling:
```
/usr/lib/gcc/x86_64-linux-gnu/11/include/popcntintrin.h: In function ‘uint64_t pthash::util::popcount(uint64_t)’:
/usr/lib/gcc/x86_64-linux-gnu/11/include/popcntintrin.h:42:1: error: inlining failed in call to ‘always_inline’ ‘long long int _mm_popcnt_u64(long long unsigned int)’: target specific option mismatch
   42 | _mm_popcnt_u64 (unsigned long long __X)
      | ^~~~~~~~~~~~~~
```
Googled for a while and found out the the problem is related to the **-mpopcnt** option, but I am not familiar with the **cmake** and the **_mm_popcnt_u64()** function.  
My system is `Linux 5.13.0-24-generic #24-Ubuntu-21.10` 
I appreciate any help to resolve this issue.

**Comment by yifangt** [comment]
Manually add the **-mpopcnt** option in the CMakeLists.txt:
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mpopcnt")`
which seems to have fixed the error.
But, obviously this is the correct way to fix the bug.

**Comment by yifangt** [comment]
Thanks! 
My gcc version is: `gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0`

**Comment by jermp** [comment]
Anyway, this issue is not related to SSHash, rather to its dependency [PTHash](https://github.com/jermp/pthash).
Can you try to compile PTHash and see if, on your machine, you get the same compiler error?

**Comment by jermp** [comment]
Actually, I just noted that also in PTHash, I've used:

    # For hardware popcount and pdep
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mbmi2 -msse4.2")

I've added them now. Can you try if now compiles on your end?

**Comment by yifangt** [comment]
Thanks!
I still have the same issue and have to manually add this line:
 `      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mpopcnt")`
However, when I switched to another computer to compile, I did not have this problem, even without the line for PTHash you mentioned.
So the issue seems be an exception on my desktop with Ubuntu 21.10.
Thanks a lot!

**Comment by jermp** [comment]
Ok. Thank you for reporting!
Closing this issue then.
