### ISSUE TITLE
question about input data

### ISSUE THREAD

**Issue by PandorasRed** [jermp/sshash#15]
hello,

i'm trying your software to see memory consumption of it for a metagenomics dataset i have, the problem is that i can't use bcalm to generate unitig for it(https://github.com/GATB/bcalm/issues/71) due to the big number of kmer, have you any software recomandation to transform a lot of read into a input format that work with your software?

**Comment by jermp** [comment]
Hi @PandorasRed,
you could try the Cuttlefish (v2) software here https://github.com/COMBINE-lab/cuttlefish
which produces a similar output to that of BCALM.
Let me know if that works for 43B of kmers. Also, what k are you using? 31?

**Comment by jermp** [comment]
I'm closing this for the moment. Let me know if you need my assistance.
