### ISSUE TITLE
Default constructor to the iterator

### ISSUE THREAD

**Issue by shokrof** [jermp/sshash#3]
Hey,
I am using sshash as submodule in my project. It will make my life much easier if you added an empty constructor for dictionary::iterator.
I am getting this error "error: no matching function for call to ‘sshash::dictionary::iterator::iterator()’".  I am not using the constructor directly but I am keeping an iterator as a member in my classes.

Thanks,
Moustafa

**Comment by jermp** [comment]
Hi,
that could be done of course but: why not keeping a pointer to an object of type `sshash::dictionary`
and then using the pointer to get the iterator, e.g., `auto it = obj->begin()`?

**Comment by shokrof** [comment]
Hi, 
I think it won't work because I want to keep the iterator data during the lifetime of my class. It is not recommended to make a pointer point to a memory on the stack(created by obj->begin()).

**Comment by shokrof** [comment]
yeah, I got thank you
