### ISSUE TITLE
Support 64-bit contig_id

### ISSUE THREAD

**Issue by jermp** [jermp/sshash#34]
This is needed to index and query large collections containing more than 2^32 contigs.
An application of this is in Fulgor, when indexing very heterogenous collections.
Tagging @rickbeeloo here and this issue https://github.com/jermp/fulgor/issues/16.

It looks like all that is needed is to refactor these two small points a little bit.

- https://github.com/jermp/sshash/blob/master/include/builder/util.hpp#L77
- https://github.com/jermp/sshash/blob/master/include/util.hpp#L21

Another point is -- for very large scale indexing -- I would suggest to use a partitioned PTHash,
rather than a single PTHash, to lower the construction time.

**Comment by jermp** [comment]
The branch https://github.com/jermp/sshash/tree/partitioned_phf already switches to partitioned PTHash and defaults to 128-bit hashes. The support for 64-bit contigs should be reflected in that branch.
CC: @rickbeeloo.

**Comment by rickbeeloo** [comment]
I just added to code I have to https://github.com/jermp/sshash/pull/36, to keep it somewhere. 
Edit, just saw your email, edit2, now also your comment above haha. 

That code worked for our queries but just going over some changes to discuss what would be best

- We took all the threads to process all chunks
```
        mphf_config.num_threads = std::thread::hardware_concurrency();
        mphf_config.num_partitions = std::thread::hardware_concurrency();
```
For our big dataset that works, but when testing I saw it's possible that the partitions get too small. I would need your help to add this check (we don't need it now but if others use it that should be there). I belief it was thrown in PThash, [here](https://github.com/jermp/pthash/blob/f30ca3d1fc4bc016aae21a79248594fe9c998870/include/builders/internal_memory_builder_partitioned_phf.hpp#L38), so we need to balance threads ~ partitions

- Any opinions about the `lookup_result` struct
 ```uint64_t kmer_id_in_contig;  // "relative" kmer-id: 0 <= kmer_id_in_contig < contig_size
    uint64_t kmer_orientation;
    uint64_t contig_id;
    uint64_t contig_size; 
```
`kmer_id_in_contig` and `contig_id` can exceed u32.  `contig_size` however, won't/shouldn't exceed u32, this was restrained to u32 in the code I removed, originally [here](https://github.com/jermp/sshash/blob/d3ea2c49eb7aad4ed544a525af3e16baab849f53/include/builder/util.hpp#L77). I think best would then chaning it back to u32, and keep the `check_contig_size` check but just not check the `pieces.size() == 1ULL << 32` (i.e. only contig size, not the number of contigs). For `kmer_orientation` we have either `0/1` so no need for u64 (p.s. just curious if you made that u32 for a reason compared to a bool).

I think that's it for sshash, will change the above after your suggestions, and then move to the small Fulgor edits

**Comment by rickbeeloo** [comment]
Aah in the [partitioned_phf](https://github.com/jermp/sshash/tree/partitioned_phf) branch you already added that check :)

**Comment by rickbeeloo** [comment]
Then it's  just these tiny changes left https://github.com/jermp/sshash/compare/partitioned_phf...rickbeeloo:sshash:partitioned_phf. 

For Fulgor we had some more changes, just u32 > u64, especially regarding the "colors" (see https://github.com/jermp/fulgor/compare/main...rickbeeloo:fulgor:main). You refactored it to mcDBG, at a glance it seems that I can refork mcDBG and just copy the changes I made before as you separated the "meta" and "normal" functions (like `intersect` and `meta_intersect`), but not sure if there is other mcDBG code I have to consider? I will soon now ;p but if you already know if/where that would help

**Comment by rickbeeloo** [comment]
> However, what is the particular reason now to enforce contig_size to be less than 2^32? Before, the reason was to also have kmer_id_in_contig < 2^32. But now, we should probably make it a uint64_t as well.

I was just thinking this cause bacterial or human genomes would never exceed  `2^32-1`. It would be a good sanity check for the input - not being some unexpected concatenation. However, plant genomes could actually exceed it, so then lets just make it `uint64_t`.

**Comment by jermp** [comment]
Yeah!

**Comment by rickbeeloo** [comment]
Hey @jermp, just trying this current branch (without my changes) on some of the example data but I get some errors for the checks. Maybe I'm missing something or giving the wrong input? 


<h2> Human chromsome test (this branch) </h2>

The chromosome you [linked on sshash](https://github.com/jermp/sshash/tree/partitioned_phf?tab=readme-ov-file#input-files)


`wget http://ftp.ensembl.org/pub/current_fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.13.fa.gz`

Instead of BCALM I used Cuttlefish for the unitigs:

`cuttlefish build -s Homo_sapiens.GRCh38.dna.chromosome.13.fa.gz -t 2 -o cuttlefish_unitigs.fasta`

Then:

`git clone https://github.com/jermp/sshash -b partitioned_phf --recursive`

build etc.
Then indexing

`./sshash/build/sshash build -i cuttlefish_unitigs.fasta.fa -k 31 -m 21 -o output.txt --check`

It will fail the check:
```
SPACE BREAKDOWN:
  minimizers: 0.465234 [bits/kmer]
  pieces: 0.0548784 [bits/kmer]
  num_super_kmers_before_bucket: 0.264572 [bits/kmer]
  offsets: 4.60858 [bits/kmer]
  strings: 2.28666 [bits/kmer]
  skew_index: 0.00131327 [bits/kmer]
  weights: 1.69477e-05 [bits/kmer]
    weight_interval_values: 2.94743e-06 [bits/kmer]
    weight_interval_lengths: 1.10529e-05 [bits/kmer]
    weight_dictionary: 2.94743e-06 [bits/kmer]
  --------------
  total: 7.68126 [bits/kmer]
checking correctness of access and positive lookup...
wrong id assigned
kmer 'AATCACTGGGACCCCTTTGACCCTCAGGCAA' not found!
ERROR: got orientation 1 but expected 0
ERROR: got curr.kmer_id 18446744073709551615 but expected 521
ERROR: got curr.kmer_id_in_contig 4294967295 but expected something < 4294967295
ERROR: got curr.contig_id 4294967295 but expected 4
ERROR: got curr.kmer_id_in_contig 4294967295 but expected 0
Segmentation fault (core dumped)
```
<h2> Simple example test</h2>

This actually is also reproducible with simple input:
```
test.fasta
>test1
ATCGATCAGCTACGACTAGCATCGACATCAGC
>test2
ATCAGCTACGATCAGCTACGATCGACTAGCAGCATCGACTACGATC
>test3
ATCATCTACGATCATCTAC
```
Then getting the unitigs with cuttlefish again, etc:
`cuttlefish build -s test.fasta -t 2 -o small_unitigs`
Gives the unitigs:
```
>9
ATCGATCAGCTACGACTAGCATCGACATCAGC
>0
ATCAGCTACGATCAGCTACGATCGACTAGCAGCATCGACTACGATC
```
Running sshash:
`./sshash/build/sshash build -i small_unitigs.fa -k 4 -m 2 -o output.txt --check`
<details>
  <summary>Long output here</summary>

  ```
k = 5, m = 2, seed = 1, l = 6, c = 3, canonical_parsing = false, weighted = false
reading file 'small_unitigs.fa'...
m_buffer_size 29411764
sorting buffer...
saving to file './sshash.tmp.run_1702480566097403174.minimizers.0.bin'...
read 2 sequences, 78 bases, 70 kmers
num_kmers 70
num_super_kmers 26
num_pieces 3 (+0.342857 [bits/kmer])
=== step 1: 'parse_file' 0.018057 [sec] (257957 [ns/kmer])
=== step 2: 'build_minimizers' 0.01381 [sec] (197286 [ns/kmer])
bits_per_offset = ceil(log2(83)) = 7
m_buffer_size 20833333
sorting buffer...
saving to file './sshash.tmp.run_1702480566129288620.bucket_pairs.0.bin'...
num_singletons 0/4 (0%)
=== step 3: 'build_index' 0.001 [sec] (14285.7 [ns/kmer])
max_num_super_kmers_in_bucket 8
log2_max_num_super_kmers_in_bucket 3
num_buckets_in_skew_index 0/4(0%)
=== step 4: 'build_skew_index' 0.00016 [sec] (2285.71 [ns/kmer])
=== total_time 0.033027 [sec] (471814 [ns/kmer])
total index size: 0.00107 [MB]
SPACE BREAKDOWN:
  minimizers: 49.6 [bits/kmer]
  pieces: 18.7429 [bits/kmer]
  num_super_kmers_before_bucket: 17.6 [bits/kmer]
  offsets: 7.31429 [bits/kmer]
  strings: 4.57143 [bits/kmer]
  skew_index: 0.914286 [bits/kmer]
  weights: 21.0286 [bits/kmer]
    weight_interval_values: 3.65714 [bits/kmer]
    weight_interval_lengths: 13.7143 [bits/kmer]
    weight_dictionary: 3.65714 [bits/kmer]
  --------------
  total: 122.286 [bits/kmer]
checking correctness of access and positive lookup...
wrong id assigned
ERROR: got orientation 0 but expected 1
ERROR: got curr.kmer_id 1 but expected 2
ERROR: got curr.kmer_id_in_contig 1 but expected 2
wrong id assigned
ERROR: got orientation 0 but expected 1
ERROR: got curr.kmer_id 47 but expected 2
ERROR: got curr.kmer_id_in_contig 19 but expected 0
ERROR: got curr.kmer_id 3 but expected 48
ERROR: got curr.contig_id 0 but expected 2
ERROR: got curr.kmer_id_in_contig 3 but expected 0
wrong id assigned
ERROR: got orientation 0 but expected 1
ERROR: got curr.kmer_id 1 but expected 20
ERROR: got curr.kmer_id_in_contig 1 but expected 20
ERROR: got curr.kmer_id 21 but expected 2
ERROR: got curr.kmer_id_in_contig 21 but expected 2
wrong id assigned
ERROR: got curr.kmer_id 4 but expected 26
ERROR: got curr.kmer_id_in_contig 4 but expected 26
wrong id assigned
wrong id assigned
ERROR: got curr.kmer_id 4 but expected 6
ERROR: got curr.kmer_id_in_contig 4 but expected 6
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
ERROR: got curr.kmer_id 35 but expected 11
ERROR: got curr.kmer_id_in_contig 7 but expected 0
wrong id assigned
ERROR: got orientation 0 but expected 1
ERROR: got curr.kmer_id 47 but expected 36
ERROR: got curr.kmer_id_in_contig 19 but expected 8
wrong id assigned
ERROR: got curr.kmer_id 3 but expected 48
ERROR: got curr.contig_id 0 but expected 2
ERROR: got curr.kmer_id_in_contig 3 but expected 0
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
ERROR: got curr.kmer_id 35 but expected 11
ERROR: got curr.kmer_id_in_contig 7 but expected 0
wrong id assigned
ERROR: got orientation 0 but expected 1
ERROR: got curr.kmer_id 47 but expected 36
ERROR: got curr.kmer_id_in_contig 19 but expected 8
ERROR: got curr.kmer_id 47 but expected 48
ERROR: got curr.kmer_id_in_contig 19 but expected 20
wrong id assigned
ERROR: got orientation 0 but expected 1
ERROR: got curr.kmer_id 1 but expected 48
ERROR: got curr.contig_id 0 but expected 2
ERROR: got curr.kmer_id_in_contig 1 but expected 0
wrong id assigned
ERROR: got curr.kmer_id 21 but expected 2
ERROR: got curr.kmer_id_in_contig 21 but expected 2
wrong id assigned
ERROR: got curr.kmer_id 12 but expected 22
ERROR: got curr.kmer_id_in_contig 12 but expected 22
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
ERROR: got curr.kmer_id 55 but expected 17
ERROR: got curr.kmer_id_in_contig 27 but expected 0
wrong id assigned
ERROR: got curr.kmer_id 17 but expected 58
ERROR: got curr.contig_id 0 but expected 2
ERROR: got curr.kmer_id_in_contig 17 but expected 0
wrong id assigned
wrong id assigned
wrong id assigned
ERROR: got curr.kmer_id 0 but expected 20
ERROR: got curr.kmer_id_in_contig 0 but expected 20
wrong id assigned
ERROR: got curr.kmer_id 21 but expected 1
ERROR: got curr.kmer_id_in_contig 21 but expected 1
wrong id assigned
ERROR: got curr.kmer_id 12 but expected 22
ERROR: got curr.kmer_id_in_contig 12 but expected 22
wrong id assigned
ERROR: got curr.kmer_id 65 but expected 14
ERROR: got curr.kmer_id_in_contig 37 but expected 0
wrong id assigned
ERROR: got curr.kmer_id 9 but expected 66
ERROR: got curr.contig_id 0 but expected 2
ERROR: got curr.kmer_id_in_contig 9 but expected 0
wrong id assigned
wrong id assigned
ERROR: got curr.kmer_id 35 but expected 11
ERROR: got curr.kmer_id_in_contig 7 but expected 0
wrong id assigned
ERROR: got curr.kmer_id 2 but expected 36
ERROR: got curr.contig_id 0 but expected 2
ERROR: got curr.kmer_id_in_contig 2 but expected 0
checked 70 kmers
EVERYTHING OK!
checking correctness of negative lookup with random kmers...
kmer 'CGATG' found!
kmer 'TGATG' found!
EVERYTHING OK!
checking correctness of navigational queries for kmers...
checked 70 kmers
EVERYTHING OK!
checking correctness of navigational queries for contigs...
checked 2 contigs
EVERYTHING OK!
checking correctness of iterator...
EVERYTHING OK!
2023-12-13 16:16:06: saving data structure to disk...
2023-12-13 16:16:06: DONE
```

</details>

**Comment by jermp** [comment]
Yes, you’re missing that unitigs are built for a given k. So of course SSHash works correctly only for the same k you used to build the unitigs. Note that cuttlefish uses k=27 by default. So that’s why k=31 and k=4 do not work as expected.You have to use the same k for both cuttlefish and SSHash.Best,-GiulioOn 13/12/2023, at 16:49, rickbeeloo ***@***.***> wrote:﻿
Hey @jermp, just trying this current branch (without my changes) on some of the example data but I get some errors for the checks. Maybe I'm missing something or giving the wrong input?
 Human chromsome test (this branch) 
The chromosome you linked on sshash
wget http://ftp.ensembl.org/pub/current_fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.13.fa.gz
Instead of BCALM I used Cuttlefish for the unitigs:
cuttlefish build -s Homo_sapiens.GRCh38.dna.chromosome.13.fa.gz -t 2 -o cuttlefish_unitigs.fasta
Then:
git clone https://github.com/jermp/sshash -b partitioned_phf --recursive
build etc.
Then indexing
./sshash/build/sshash build -i cuttlefish_unitigs.fasta.fa -k 31 -m 21 -o output.txt --check
It will fail the check:
SPACE BREAKDOWN:
  minimizers: 0.465234 [bits/kmer]
  pieces: 0.0548784 [bits/kmer]
  num_super_kmers_before_bucket: 0.264572 [bits/kmer]
  offsets: 4.60858 [bits/kmer]
  strings: 2.28666 [bits/kmer]
  skew_index: 0.00131327 [bits/kmer]
  weights: 1.69477e-05 [bits/kmer]
    weight_interval_values: 2.94743e-06 [bits/kmer]
    weight_interval_lengths: 1.10529e-05 [bits/kmer]
    weight_dictionary: 2.94743e-06 [bits/kmer]
  --------------
  total: 7.68126 [bits/kmer]
checking correctness of access and positive lookup...
wrong id assigned
kmer 'AATCACTGGGACCCCTTTGACCCTCAGGCAA' not found!
ERROR: got orientation 1 but expected 0
ERROR: got curr.kmer_id 18446744073709551615 but expected 521
ERROR: got curr.kmer_id_in_contig 4294967295 but expected something < 4294967295
ERROR: got curr.contig_id 4294967295 but expected 4
ERROR: got curr.kmer_id_in_contig 4294967295 but expected 0
Segmentation fault (core dumped)

 Simple example test
This actually is also reproducible with simple input:
test.fasta
>test1
ATCGATCAGCTACGACTAGCATCGACATCAGC
>test2
ATCAGCTACGATCAGCTACGATCGACTAGCAGCATCGACTACGATC
>test3
ATCATCTACGATCATCTAC

Then getting the unitigs with cuttlefish again, etc:
cuttlefish build -s test.fasta -t 2 -o small_unitigs
Gives the unitigs:
>9
ATCGATCAGCTACGACTAGCATCGACATCAGC
>0
ATCAGCTACGATCAGCTACGATCGACTAGCAGCATCGACTACGATC

Running sshash:
./sshash/build/sshash build -i small_unitigs.fa -k 4 -m 2 -o output.txt --check

  Long output here
k = 5, m = 2, seed = 1, l = 6, c = 3, canonical_parsing = false, weighted = false
reading file 'small_unitigs.fa'...
m_buffer_size 29411764
sorting buffer...
saving to file './sshash.tmp.run_1702480566097403174.minimizers.0.bin'...
read 2 sequences, 78 bases, 70 kmers
num_kmers 70
num_super_kmers 26
num_pieces 3 (+0.342857 [bits/kmer])
=== step 1: 'parse_file' 0.018057 [sec] (257957 [ns/kmer])
=== step 2: 'build_minimizers' 0.01381 [sec] (197286 [ns/kmer])
bits_per_offset = ceil(log2(83)) = 7
m_buffer_size 20833333
sorting buffer...
saving to file './sshash.tmp.run_1702480566129288620.bucket_pairs.0.bin'...
num_singletons 0/4 (0%)
=== step 3: 'build_index' 0.001 [sec] (14285.7 [ns/kmer])
max_num_super_kmers_in_bucket 8
log2_max_num_super_kmers_in_bucket 3
num_buckets_in_skew_index 0/4(0%)
=== step 4: 'build_skew_index' 0.00016 [sec] (2285.71 [ns/kmer])
=== total_time 0.033027 [sec] (471814 [ns/kmer])
total index size: 0.00107 [MB]
SPACE BREAKDOWN:
minimizers: 49.6 [bits/kmer]
pieces: 18.7429 [bits/kmer]
num_super_kmers_before_bucket: 17.6 [bits/kmer]
offsets: 7.31429 [bits/kmer]
strings: 4.57143 [bits/kmer]
skew_index: 0.914286 [bits/kmer]
weights: 21.0286 [bits/kmer]
  weight_interval_values: 3.65714 [bits/kmer]
  weight_interval_lengths: 13.7143 [bits/kmer]
  weight_dictionary: 3.65714 [bits/kmer]
--------------
total: 122.286 [bits/kmer]
checking correctness of access and positive lookup...
wrong id assigned
ERROR: got orientation 0 but expected 1
ERROR: got curr.kmer_id 1 but expected 2
ERROR: got curr.kmer_id_in_contig 1 but expected 2
wrong id assigned
ERROR: got orientation 0 but expected 1
ERROR: got curr.kmer_id 47 but expected 2
ERROR: got curr.kmer_id_in_contig 19 but expected 0
ERROR: got curr.kmer_id 3 but expected 48
ERROR: got curr.contig_id 0 but expected 2
ERROR: got curr.kmer_id_in_contig 3 but expected 0
wrong id assigned
ERROR: got orientation 0 but expected 1
ERROR: got curr.kmer_id 1 but expected 20
ERROR: got curr.kmer_id_in_contig 1 but expected 20
ERROR: got curr.kmer_id 21 but expected 2
ERROR: got curr.kmer_id_in_contig 21 but expected 2
wrong id assigned
ERROR: got curr.kmer_id 4 but expected 26
ERROR: got curr.kmer_id_in_contig 4 but expected 26
wrong id assigned
wrong id assigned
ERROR: got curr.kmer_id 4 but expected 6
ERROR: got curr.kmer_id_in_contig 4 but expected 6
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
ERROR: got curr.kmer_id 35 but expected 11
ERROR: got curr.kmer_id_in_contig 7 but expected 0
wrong id assigned
ERROR: got orientation 0 but expected 1
ERROR: got curr.kmer_id 47 but expected 36
ERROR: got curr.kmer_id_in_contig 19 but expected 8
wrong id assigned
ERROR: got curr.kmer_id 3 but expected 48
ERROR: got curr.contig_id 0 but expected 2
ERROR: got curr.kmer_id_in_contig 3 but expected 0
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
ERROR: got curr.kmer_id 35 but expected 11
ERROR: got curr.kmer_id_in_contig 7 but expected 0
wrong id assigned
ERROR: got orientation 0 but expected 1
ERROR: got curr.kmer_id 47 but expected 36
ERROR: got curr.kmer_id_in_contig 19 but expected 8
ERROR: got curr.kmer_id 47 but expected 48
ERROR: got curr.kmer_id_in_contig 19 but expected 20
wrong id assigned
ERROR: got orientation 0 but expected 1
ERROR: got curr.kmer_id 1 but expected 48
ERROR: got curr.contig_id 0 but expected 2
ERROR: got curr.kmer_id_in_contig 1 but expected 0
wrong id assigned
ERROR: got curr.kmer_id 21 but expected 2
ERROR: got curr.kmer_id_in_contig 21 but expected 2
wrong id assigned
ERROR: got curr.kmer_id 12 but expected 22
ERROR: got curr.kmer_id_in_contig 12 but expected 22
wrong id assigned
wrong id assigned
wrong id assigned
wrong id assigned
ERROR: got curr.kmer_id 55 but expected 17
ERROR: got curr.kmer_id_in_contig 27 but expected 0
wrong id assigned
ERROR: got curr.kmer_id 17 but expected 58
ERROR: got curr.contig_id 0 but expected 2
ERROR: got curr.kmer_id_in_contig 17 but expected 0
wrong id assigned
wrong id assigned
wrong id assigned
ERROR: got curr.kmer_id 0 but expected 20
ERROR: got curr.kmer_id_in_contig 0 but expected 20
wrong id assigned
ERROR: got curr.kmer_id 21 but expected 1
ERROR: got curr.kmer_id_in_contig 21 but expected 1
wrong id assigned
ERROR: got curr.kmer_id 12 but expected 22
ERROR: got curr.kmer_id_in_contig 12 but expected 22
wrong id assigned
ERROR: got curr.kmer_id 65 but expected 14
ERROR: got curr.kmer_id_in_contig 37 but expected 0
wrong id assigned
ERROR: got curr.kmer_id 9 but expected 66
ERROR: got curr.contig_id 0 but expected 2
ERROR: got curr.kmer_id_in_contig 9 but expected 0
wrong id assigned
wrong id assigned
ERROR: got curr.kmer_id 35 but expected 11
ERROR: got curr.kmer_id_in_contig 7 but expected 0
wrong id assigned
ERROR: got curr.kmer_id 2 but expected 36
ERROR: got curr.contig_id 0 but expected 2
ERROR: got curr.kmer_id_in_contig 2 but expected 0
checked 70 kmers
EVERYTHING OK!
checking correctness of negative lookup with random kmers...
kmer 'CGATG' found!
kmer 'TGATG' found!
EVERYTHING OK!
checking correctness of navigational queries for kmers...
checked 70 kmers
EVERYTHING OK!
checking correctness of navigational queries for contigs...
checked 2 contigs
EVERYTHING OK!
checking correctness of iterator...
EVERYTHING OK!
2023-12-13 16:16:06: saving data structure to disk...
2023-12-13 16:16:06: DONE

**Comment by rickbeeloo** [comment]
How did I miss that... Thanks!
Then I keep that as as simple test for everything:
```
wget http://ftp.ensembl.org/pub/current_fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.13.fa.gz
cuttlefish build -s Homo_sapiens.GRCh38.dna.chromosome.13.fa.gz -t 2 -k 31 -o cuttlefish_unitigs.fasta
sshash build -i cuttlefish_unitigs.fasta.fa -k 31 -m 21 -o output.txt --check
```

(that indeed works)

Any suggestions on how we will properly test `u64` sshash/fulgor? We can't really run `--check` on our big dataset to test sshash/fulgor after editing as it will take ages. We could generate `2^32` kmers (k>16), and perhaps make some concatenation of them to have long "contigs" and test navigational queries. Alternatively, we can add big numbers to the variables in sshash directly but perhaps not the safest test idea (especially not if I do it haha). Let me know :)

**Comment by jermp** [comment]
No problem! Just keep in mind that a dBG is built for a specific value of k, and that value only must be used.

For the testing, well we could just let in run :) Yes, it will probably take days, if not weeks, on that index.
Otherwise, we sample some queries and check only them.

**Comment by rickbeeloo** [comment]
(Just as a note, we shouldn't forget to add something about increasing `ulimit` to the readme of this fork, just encountered [this](https://github.com/jermp/fulgor/issues/16#issuecomment-1693015018) again, so probably that will happen often for big datasets)

**Comment by jermp** [comment]
Thanks @rickbeeloo for reporting! I'm adding this to the readme of this branch: https://github.com/jermp/sshash/tree/partitioned_phf.

**Comment by jermp** [comment]
Ok, done as of https://github.com/jermp/sshash/commit/119accf0c98eaedf0036f41d2c61bca1d94c661c.
I've added the same note in Fulgor as well.

**Comment by rickbeeloo** [comment]
Hey :) 

**Fulgor**
Regarding the `colors` (like [here](https://github.com/jermp/fulgor/blob/435826986b8568dd2fe3a707f8fbf54ca0ec3dc8/src/psa/full_intersection.cpp#L206) but also [here ](https://github.com/jermp/fulgor/blob/435826986b8568dd2fe3a707f8fbf54ca0ec3dc8/include/color_classes/meta.hpp#L138-L143)in meta for example) which refers to the origin of the untigs, or the partitions for the mcDBG. These colors can technically also exceed `u32`, although maybe unlikely to happen. To be safe we also up that to `u64`?

**SShash**
Like you mentioned at the start this is just [only two changes now](https://github.com/jermp/sshash/compare/partitioned_phf...rickbeeloo:sshash:partitioned_phf). I will first test that on `2^32` unique 17-mers, that is `129GB` so not that gigigantic, then at least `--check` will be faster. It can't check navigational queries really as it's just 17 mers in the FASTA but we can then later sample that on the big index. Just thought it would be quite sad to wait weeks just to realize membership queries already failed.

Could you elaborate on `c` and `l` I understand they reflect the space/time trade-off but I couldn't get from the docs if I should put these low or high if I don't care about space. We have tons of space, so I would prefer faster construction over minimizing storage/RAM (for testing)

Have a good Saturday :)

**Comment by rickbeeloo** [comment]
I now made these changes: https://github.com/jermp/fulgor/compare/main...rickbeeloo:fulgor:main.
Some notes:
1. I think the `num_docs` will realistically never be `2^32+`, that would be a lot of files. So I left this at `uint32`. Related to this we have the `colors` which come from GGCAT and also reflect the input files, for the same reason I left these `uint32`. If we would actually want to have `uint64` colors that would require more refactoring, and also running GGCAT with `uint64` (I suppose [here](https://github.com/algbio/ggcat/blob/553e6b1b9804b0aebe24bc9b30c8962027f4bbb6/crates/config/src/lib.rs#L12))
2. In the meta colored paper you say you cluster the references based on the shared unitigs. From this I assume the `partitions` are always <= `num_docs`, is that correct? If so we can leave that `uint32` as well in line with 1
3. We spoke about having big contigs, like plants, where a kmer can have a position on the contig `2^32+`. Hence I changed the code [here](https://github.com/rickbeeloo/fulgor/blob/2f5bbe4ea0fe7da10a1dcb1637f0a85d40e41337/piscem_psa/projected_hits.hpp#L6-L16) with `contigIdx_` and `contigLen_`  being `uint64` but there are other things like [the offset ](https://github.com/rickbeeloo/fulgor/blob/2f5bbe4ea0fe7da10a1dcb1637f0a85d40e41337/piscem_psa/hit_searcher.cpp#L498) and `invalid_cid` probably having to be replaced by `sshash::constants::invalid_uint64` etc. But I'm not sure how this skipping exactly works so I could use some help there :)

**Comment by rickbeeloo** [comment]
Hey @jermp  :)

The `--check` for sshash on `2^32` 17-mers finsihed without errors so we know at least the lookups go well. 

For fulgor, I get some error regarding:
```
../src/psa/full_intersection.cpp:225:9: error: no match for ‘operator=’ (operand types are ‘__gnu_cxx::__normal_iterator<long unsigned int*, std::vector<long unsigned int> >’ and ‘__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int> >’)
  225 |     end = std::unique(tmp.begin(), tmp.end());
```
As I said before I'm not that familiar with C++ so I don't think it's smart if I just start adding code to solve that. Could you try to compile: https://github.com/rickbeeloo/fulgor (it does use the `partitioned_hpf` branch already but without the two changes we need for int64 - but don't think that is the problem)
Can you look with me what still goes wrong?

**Comment by jermp** [comment]
Hi Rick,
the problem looks like you forgot to change `std::vector<uint32_t>` into `std::vector<uint64_t>`.
Will try to compile your branch to verify this.

**Comment by rickbeeloo** [comment]
Sure, curious to see what was wrong. It might not be the only thing😅

**Comment by jermp** [comment]
This line causes the problem https://github.com/rickbeeloo/fulgor/blob/main/src/psa/full_intersection.cpp#L225
because `end` has type `std::vector<uint64_t>::iterator` (after making unitig ids 64-bit ints) and we try to assign it to the result of `std::unique` with `vector<uint32_t>`, so something that has type `std::vector<uint32_t>::iterator`. Just cannot convert iterator types.

Below the correct code:

    template <typename ColorClasses>
    void index<ColorClasses>::intersect_unitigs(std::vector<uint64_t>& unitig_ids,
                                                std::vector<uint32_t>& colors) const {
        /* here we use it to hold the color class ids;
           in meta_intersect we use it to hold the partition ids */
        std::vector<uint32_t> tmp;
        std::vector<typename ColorClasses::iterator_type> iterators;
    
        /* deduplicate unitig_ids */
        std::sort(unitig_ids.begin(), unitig_ids.end());
        auto end_unitig_ids = std::unique(unitig_ids.begin(), unitig_ids.end());
        tmp.reserve(end_unitig_ids - unitig_ids.begin());
        for (auto it = unitig_ids.begin(); it != end_unitig_ids; ++it) {
            uint64_t unitig_id = *it;
            uint32_t color_class_id = u2c(unitig_id);
            tmp.push_back(color_class_id);
        }
    
        /* deduplicate color class ids */
        std::sort(tmp.begin(), tmp.end());
        auto end_tmp = std::unique(tmp.begin(), tmp.end());
        iterators.reserve(end_tmp - tmp.begin());
        for (auto it = tmp.begin(); it != end_tmp; ++it) {
            uint64_t color_class_id = *it;
            auto fwd_it = m_ccs.colors(color_class_id);
            iterators.push_back(fwd_it);
        }
    
        tmp.clear();  // don't need color class ids anymore
        if constexpr (ColorClasses::meta_colored) {
            meta_intersect(iterators, colors, tmp);
        } else {
            intersect(iterators, colors, tmp);
        }
    
        assert(util::check_intersection(iterators, colors));
    }

**Comment by rickbeeloo** [comment]
Cool! Then that should be it for Fulgor :)

I mentioned in the sshash pr that I was planning to use the [unique kmers]( https://github.com/rickbeeloo/UniqueMers) to generate kmers with random sequence suffixes. However, Looking at our dataset again the unitigs were `477GB` whereas randomly generating data would also be between `150-200GB` depending on the suffix length. So I will just run Fulgor on the entire dataset. 

1) Are there any things you think I forgot in https://github.com/rickbeeloo/fulgor before I run it?
2) Now we rerun Fulgor again to be sure everything was constructed correctly, should we use meta colored?

**Comment by jermp** [comment]
> 1. Are there any things you think I forgot in https://github.com/rickbeeloo/fulgor before I run it?

Looks good to me. Try it!



> 2. Now we rerun Fulgor again to be sure everything was constructed correctly, should we use meta colored?

Yeah, why not? But first, we have to build a "normal" Fulgor index which we then transform into the meta-colored version.

**Comment by rickbeeloo** [comment]
It's building🤞
(Well it already was but forgot the `ulimit -n 2048` again 😅)

----

When testing Fulgor on the mock data (kmers of 17 with 0..35 random nts after it) I kept getting the `"seed did not work"` [from pthash](https://github.com/jermp/pthash/blob/f30ca3d1fc4bc016aae21a79248594fe9c998870/include/builders/util.hpp#L71). That probably has to do with the data and not the changes but to prevent that one should just try another seed?

**Comment by jermp** [comment]
Ok, done as of https://github.com/jermp/sshash/commit/fbe00d9f1ca4fa875177deba11a7e9b9e5c2b71a.
(Not yet merged in `master`. For now in `partitioned_phf` branch.)

**Comment by jermp** [comment]
Hi @rickbeeloo,

> When testing Fulgor on the mock data (kmers of 17 with 0..35 random nts after it) I kept getting the `"seed did not work"` [from pthash](https://github.com/jermp/pthash/blob/f30ca3d1fc4bc016aae21a79248594fe9c998870/include/builders/util.hpp#L71). That probably has to do with the data and not the changes but to prevent that one should just try another seed?

I'm not sure what you did here, but this is surely due to repeated kmers in the input.

**Comment by rickbeeloo** [comment]
Hi @jermp, I will check it again. 

I'm now using https://github.com/jermp/sshash/commit/fbe00d9f1ca4fa875177deba11a7e9b9e5c2b71a in my branch https://github.com/rickbeeloo/fulgor/tree/skipcdbg. Just restarted fulgor for the big dataset (cause it failed on [an assert you added](https://github.com/jermp/fulgor/blob/0d989234587ac962f1b43a5ae7f7936edf470417/include/builder.hpp#L73), which I missed).

Btw in that branch I hardcoded skipping the building of the cdbg. I think using an already existing GGCAT output is neat to have, especially for these bigger datasets. 

Lets see if it makes it through this time 🙏

**Comment by jermp** [comment]
Hi Rick, ok good.
Well, you built the whole index once, so we know for sure it will make it :)

> I think using an already existing GGCAT output is neat to have, especially for these bigger datasets.

Yes, absolutely!
