### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jnalanko** [jermp/sshash#7]
Hi, I'm getting this Segmentation fault. Am I doing something stupid or is it a bug?

```
./build/build test.fa 31 13 -o ./index/out.sshash

k = 31, m = 13, seed = 1, l = 6, c = 3, canonical_parsing = false, weighted = false
reading file 'test.fa'...
m_buffer_size 29411764
sorting buffer...
saving to file './sshash.tmp.run_1653987257158295118.minimizers.0.bin'...
read 1 sequences, 63 bases, 33 kmers
num_kmers 33
num_super_kmers 4
num_pieces 2 (+3.63636 [bits/kmer])
=== step 1: 'parse_file' 7.9e-05 [sec] (2393.94 [ns/kmer])
Segmentation fault
```

This is the file test.fna (I had to change the extension to .txt for github because github did not allow .fa file extension).

[test.txt](https://github.com/jermp/sshash/files/8803687/test.txt)

**Comment by jermp** [comment]
Hi, yes I can confirm the segfault also on my end.
I'm looking into this now. Thank you for reporting!
(Have you tried also the other test files in `/data`? They work correctly for me.)

Anyway, it seems a problem with the ext-mem construction (latest commit).
I tried the commit before release 2.0.1 (c48948c0f5882063deeb6702f518d187ad7c7a07)
and everything worked.
Can you confirm this?

**Comment by jnalanko** [comment]
I can confirm that data/unitigs_stitched/ecoli1_k31_ust.fa.gz works in the latest commit, and commit c48948c works for the file that caused the segfault.

**Comment by jermp** [comment]
Yeah, it's some silly corner cases for tiny files where a tmp file results empty.
I'm fixing this now and will let you know.

**Comment by jermp** [comment]
As of latest commit (480f1da593e4550422ce8ead6540b24485897641), it should be fixed.
I can confirm it works on my end.
Can you check? Thanks!

**Comment by jermp** [comment]
Ok, I'm closing this.
